### ISSUE TITLE
Facebook Graph returned an error: Error validating verification code

### ISSUE THREAD

**Issue by ivangretsky** [jmartsch/processwire-social-login#3]
Good day!

Thanks for taking care of this module, making it PW3 compatible!

I am trying to make it work with facebook. I have followed the readme instructions, but am getting an error I can't really understand. 

This is from the errors.txt log:

`
2020-05-16 21:13:11	guest	http://localhost/pw/social-login/	Error: 	Exception: Facebook Graph returned an error: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request (in XYZ\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Auth.php line 169)
`

This is from the exceptions.txt log:

`
2020-05-16 21:13:11	guest	http://localhost/pw/social-login/?provider=facebook	Facebook Graph returned an error: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request (in XYZ\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Auth.php line 169)
`

I am pretty sure I got Facebook app configured right as I managed to make [this module](https://github.com/ryancramerdesign/LoginFacebook) work with it.

Could you please provide any help?

**Comment by jmartsch** [comment]
This seems to be an error with HybridAuth, not my module. Please take a look at this issue here: https://github.com/hybridauth/hybridauth/issues/990

**Comment by ivangretsky** [comment]
I got an [answer](https://github.com/hybridauth/hybridauth/issues/990#issuecomment-630173987) in the hybridauth issues. I am not sure I quite understand it, Could you please chech if that is something wrong on my side or the module?

**Comment by ivangretsky** [comment]
Hey @jmartsch! I know you probably do not have enough time to solve all the issues straight away. But could you predict the future a bit? Would you have time to come back to this anytime soon?

**Comment by jmartsch** [comment]
Hey Ivan, I am really sorry, but I can not help you with that at the moment. This is a module isn't maintained anymore.

Please check if the redirect_uri really is the same as in the OAuth request. Thats what the error says.

If you find a solution, it would be nice if you could open a PR or give some hints.

**Comment by ivangretsky** [comment]
I got it. I you can write where do I "check if the redirect_uri really is the same as in the OAuth request" or give at least some hints I would be thankful and would write back if I manage to solve the issue.

**Comment by jmartsch** [comment]
Really can not say where you find it, and I don't have a setup at all. I think it is somewhere in Facebooks app settings, where you put the redirect URL. It is not a setting in the module, but in Facebook, I think.

**Comment by jmartsch** [comment]
Take a look at this answer here: https://stackoverflow.com/a/56288017/616067

Search for the error on google and stackoverflow. Maybe there you find some answers.
